-- Core voting schema for Cloudflare D1 (SQLite).
-- IDs are generated by the Worker with crypto.randomUUID().

CREATE TABLE families (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  family_token TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL
) STRICT;

CREATE TABLE swimmers (
  id TEXT PRIMARY KEY,
  family_id TEXT NOT NULL,
  name TEXT NOT NULL,
  group_name TEXT,
  created_at TEXT NOT NULL,
  CONSTRAINT swimmers_family_fk
    FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE RESTRICT
) STRICT;

CREATE TABLE voting_settings (
  id INTEGER PRIMARY KEY,
  is_open INTEGER NOT NULL DEFAULT 1 CHECK (is_open IN (0, 1)),
  closed_at TEXT,
  updated_at TEXT NOT NULL,
  updated_by TEXT,
  CONSTRAINT voting_settings_singleton CHECK (id = 1)
) STRICT;

CREATE TABLE votes (
  id TEXT PRIMARY KEY,
  voter_id TEXT NOT NULL UNIQUE,
  candidate_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  CONSTRAINT votes_voter_fk
    FOREIGN KEY (voter_id) REFERENCES swimmers(id) ON DELETE RESTRICT,
  CONSTRAINT votes_candidate_fk
    FOREIGN KEY (candidate_id) REFERENCES swimmers(id) ON DELETE RESTRICT
) STRICT;

CREATE TABLE admins (
  email TEXT PRIMARY KEY COLLATE NOCASE,
  created_at TEXT NOT NULL
) STRICT;

CREATE INDEX swimmers_family_id_idx ON swimmers(family_id);
CREATE INDEX swimmers_name_idx ON swimmers(name COLLATE NOCASE);
CREATE INDEX votes_candidate_id_idx ON votes(candidate_id);

INSERT INTO voting_settings (id, is_open, updated_at)
VALUES (1, 1, '1970-01-01T00:00:00.000Z');

CREATE VIEW swimmer_roster AS
SELECT id, name
FROM swimmers
ORDER BY name COLLATE NOCASE, id;

CREATE VIEW admin_roster AS
SELECT
  f.id AS family_id,
  f.email AS family_email,
  f.family_token,
  s.id AS swimmer_id,
  s.name AS swimmer_name,
  s.group_name,
  EXISTS (
    SELECT 1
    FROM votes v
    WHERE v.voter_id = s.id
  ) AS has_voted
FROM families f
JOIN swimmers s ON s.family_id = f.id
ORDER BY COALESCE(s.group_name, ''), f.email, s.name, s.id;

CREATE VIEW vote_results AS
SELECT
  s.id AS candidate_id,
  s.name AS candidate_name,
  COUNT(v.id) AS vote_count
FROM swimmers s
LEFT JOIN votes v ON v.candidate_id = s.id
GROUP BY s.id, s.name
ORDER BY COUNT(v.id) DESC, s.name COLLATE NOCASE, s.id;
